use_frameworks!

platform :ios, '10.0'

target 'notifyvisitorsNudges_Example' do
  pod 'notifyvisitorsNudges', :path => '../'

  target 'notifyvisitorsNudges_Tests' do
    inherit! :search_paths

    
  end
end
